import math
a=float(input('enter a value:'))
b=int(input('enter b value:'))
c=float(input('enter c value:'))
d=math.sqrt(a)
e=math.factorial(b)
f=math.pow(c,3)
print("sqrt",d)
print('factorial',e)
print('power',f)
