#arithmetic operators
a=int(input('enter a value:'))
b=int(input('enter b value:'))
print('addition =',(a+b))
print('subraction =',(a-b))
print('multiplication =',(a*b))
print('division =',(a/b))
print('modulus =',(a%b))
print('exponent =',(a**3))
print('floor division =',(a//b))
